# Generated by Django 4.2.20 on 2025-04-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_remove_basket_items_alter_basket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
