# Generated by Django 4.2.20 on 2025-04-13 21:46

from django.db import migrations

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('grocery', 'UserProfile')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(
            user=user,
            defaults={
                'bio': '',
                'preferred_categories': '',
                'avatar': 'default-avatar.png'
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_alter_basket_user_alter_basket_unique_together'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
