# Generated by Django 4.2.20 on 2025-04-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_alter_basket_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
